version: 2
updates:
- package-ecosystem: pip
  directory: /docker/pcap-http-extractor
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /docker/pcap-http-extractor
  schedule:
    interval: daily
